<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="kundesh" failures="0" tests="6" name="com.eva.vtiger.testscripts.MarketingAccountTestScripts" time="2.732" errors="1" timestamp="2023-10-26T13:27:02 IST" skipped="5">
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="verifyVT005AccountEditable" time="2.732">
    <skipped/>
  </testcase> <!-- verifyVT005AccountEditable -->
  <system-out/>
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="verifyVT004DuplicateAccount" time="0.000">
    <skipped/>
  </testcase> <!-- verifyVT004DuplicateAccount -->
  <system-out/>
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="beforeTestcase" time="0.000">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.eva.vtiger.testscripts.BaseTest.beforeTestcase(BaseTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeTestcase -->
  <system-out/>
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="verifyVT001CreateAccount" time="0.000">
    <skipped/>
  </testcase> <!-- verifyVT001CreateAccount -->
  <system-out/>
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="verifyVT003SearchAccount" time="0.000">
    <skipped/>
  </testcase> <!-- verifyVT003SearchAccount -->
  <system-out/>
  <testcase classname="com.eva.vtiger.testscripts.MarketingAccountTestScripts" name="verifyVT002DeleteAccount" time="0.000">
    <skipped/>
  </testcase> <!-- verifyVT002DeleteAccount -->
  <system-out/>
</testsuite> <!-- com.eva.vtiger.testscripts.MarketingAccountTestScripts -->
